;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Attack.Light",DevComment="")
+GameplayTagList=(Tag="Boss.Attack",DevComment="")
+GameplayTagList=(Tag="Data.ArmorDefense",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.EnemyDamage",DevComment="")
+GameplayTagList=(Tag="Data.RestoreHealth",DevComment="")
+GameplayTagList=(Tag="Data.RestoreStamina",DevComment="")
+GameplayTagList=(Tag="Enemy.Ability.Attack",DevComment="")
+GameplayTagList=(Tag="Enemy.Ability.Death",DevComment="")
+GameplayTagList=(Tag="Enemy.Ability.ShootProjectile",DevComment="")
+GameplayTagList=(Tag="Enemy.Cooldown.GetHit",DevComment="")
+GameplayTagList=(Tag="Enemy.State.Dead",DevComment="")
+GameplayTagList=(Tag="Enemy.State.GetHit",DevComment="")
+GameplayTagList=(Tag="Event.Enemy.Death",DevComment="")
+GameplayTagList=(Tag="Event.Enemy.EnemyHitCheck",DevComment="")
+GameplayTagList=(Tag="Event.Enemy.GetHit",DevComment="")
+GameplayTagList=(Tag="Event.Enemy.ShootProjectile",DevComment="")
+GameplayTagList=(Tag="Event.Melee.Hitbox.Off",DevComment="")
+GameplayTagList=(Tag="Event.Melee.Hitbox.On",DevComment="")
+GameplayTagList=(Tag="Event.Player.HitCheck",DevComment="")
+GameplayTagList=(Tag="InputTag.Attack.Primary",DevComment="")
+GameplayTagList=(Tag="Player.Ability.Attack",DevComment="")
+GameplayTagList=(Tag="Player.Ability.Emote",DevComment="")
+GameplayTagList=(Tag="Player.Ability.Evasion",DevComment="")
+GameplayTagList=(Tag="State.Action",DevComment="")
+GameplayTagList=(Tag="State.Attack",DevComment="")
+GameplayTagList=(Tag="State.Moving",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee.Club",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee.Woodclub",DevComment="")

